# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CED K-12 TLE Taxonomy
tagline:          'CED K-12 TLE Taxonomy'
description:      ''
url:              https://isislab-unisa.github.io/tle_taxonomy/
baseurl:          /

paginate:         5

github:
  repo:           https://github.com/isislab-unisa/tle_taxonomy/
